### PR TITLE
Fix AD for parameters

### LINKED ISSUE #99: Zygote tutorial broken
https://docs.sciml.ai/dev/modules/Integrals/tutorials/differentiating_integrals/

``` julia
using Integrals, ForwardDiff, FiniteDiff, Zygote, IntegralsCuba
f(x,p) = sum(sin.(x .* p))
lb = ones(2)
ub = 3ones(2)
p = [1.5,2.0]

function testf(p)
    prob = IntegralProblem(f,lb,ub,p)
    sin(solve(prob,CubaCuhre(),reltol=1e-6,abstol=1e-6)[1])
end
dp1 = Zygote.gradient(testf,p)
dp2 = FiniteDiff.finite_difference_gradient(testf,p)
dp3 = ForwardDiff.gradient(testf,p)
dp1[1] ≈ dp2 ≈ dp3
```
```julia
julia> Zygote.gradient(testf,p)
ERROR: BoundsError: attempt to access 0-element Vector{Any} at index []
...
```

### PR DESCRIPTION
**Pull request by lxvm**
This pr should fix #99 but in writing this I ran into a lot of internal inconsistencies in Integrals.jl as to how it handles the behavior of nout, batch, and inplace integration (as defined in the docs for `IntegralProblem`). Moreover, there are two ambiguities that mean I can't make autodiff type stable:
1. When nout = 1, batch = 0, and not inplace, it is unclear whether the integrand returns a scalar or a vector of length one
2. When nout = 1 and not inplace, it is unclear if the algorithm should return a scalar or a vector of length 1. In fact the different algorithms make different choices.

This pr also creates breaking changes in IntegralsCubature.jl because a) it did not follow the interface in the docs (i.e. in places it used adjoints to turn vectors into matrices where it was not supposed to) and b) I changed the default choice regarding point 2. above to return a scalar when nout = 1.

In light of these points, I advocate for merging this pr, and also making the following changes in the next breaking release of Integrals.jl
* Features of inplace integrands, `nout`, and `batch` should be replaced by specialized integrand wrappers that allow the user to provide the output (and input) arrays of the correct Julia types, which can be arbitrary. (I believe this is the right abstraction and have implemented it in https://github.com/lxvm/AutoBZCore.jl)
* It seems like `IntegralSolution`s are treated like arrays, so we should decide how to interpret the output of algorithms in terms of this so we can write type-stable pullbacks.
* The C library wrappers (i.e. IntegralsCuba.jl and IntegralsCubature.jl), which have restricted integrand types of floats or float arrays, may need their own AD package extensions if we would like to implement more efficient pullbacks for pure Julia packages with more generic types. For example, it would be nice to calculate the integral of a function over an ellipse and calculate its partials w.r.t. the semiaxes of the ellipse. I don't see anything preventing this in a pure Julia implementation, but the code may have to be different from the C code.
* Is it possible to replace the `sensealg` argument with different AD backends provided by AbstractDifferentiation.jl?

Thanks in advance for your help.

### CODE REVIEW

**Comment by ArnoStrouwen** [comment]
> * Features of inplace integrands, `nout`, and `batch` should be replaced by specialized integrand wrappers that allow the user to provide the output (and input) arrays of the correct Julia types, which can be arbitrary. (I believe this is the right abstraction and have implemented it in https://github.com/lxvm/AutoBZCore.jl)

Yes, `nout` and maybe `batch` needs to be removed, and replaced with a prototype container passed by the user. 

> * It seems like `IntegralSolution`s are treated like arrays, so we should decide how to interpret the output of algorithms in terms of this so we can write type-stable pullbacks.

I would try to make the behaviour of the solutions as similar as possible to how this is handled for AD of `ODEProblem`.

> * The C library wrappers (i.e. IntegralsCuba.jl and IntegralsCubature.jl), which have restricted integrand types of floats or float arrays, may need their own AD package extensions if we would like to implement more efficient pullbacks for pure Julia packages with more generic types. For example, it would be nice to calculate the integral of a function over an ellipse and calculate its partials w.r.t. the semiaxes of the ellipse. I don't see anything preventing this in a pure Julia implementation, but the code may have to be different from the C code.

I'm not sure if I understand what aspect of the ellipse is being nudged here. Do you mean how the integral would change if one of the axes were to change in length a bit? If so, indeed we need better AD for handling the boundaries of the integration domain. Getting it working for the bounds of a box would already be a great improvement.

> * Is it possible to replace the `sensealg` argument with different AD backends provided by AbstractDifferentiation.jl?

I would hold off on this until `AbstractDifferentiation` is more mature. I don't think any of the other SciML solver packages made the switch already?

**Comment by ChrisRackauckas** [comment]
> I would hold off on this until AbstractDifferentiation is more mature. I don't think any of the other SciML solver packages made the switch already?

It's not ready. It doesn't cache.

**Comment by ChrisRackauckas** [comment]
> Yes, nout and maybe batch needs to be removed, and replaced with a prototype container passed by the user.

Agreed, that interface just needs to change.

**Comment by ChrisRackauckas** [comment]
> Features of inplace integrands, nout, and batch should be replaced by specialized integrand wrappers that allow the user to provide the output (and input) arrays of the correct Julia types, which can be arbitrary. (I believe this is the right abstraction and have implemented it in https://github.com/lxvm/AutoBZCore.jl)

Yeah this is as discussed in https://github.com/SciML/Integrals.jl/issues/169. We should change the interface, just no one has gotten around to doing it.

> It seems like IntegralSolutions are treated like arrays, so we should decide how to interpret the output of algorithms in terms of this so we can write type-stable pullbacks.

It just needs a few overloads like https://github.com/SciML/SciMLBase.jl/blob/master/src/solutions/zygote.jl

File: ext/IntegralsForwardDiffExt.jl [hunk 1]
```diff
@@ -29,7 +29,8 @@ function Integrals.__solvebp(cache, alg, sensealg, lb, ub,
         dfdp = function (out, x, p)
             dualp = reinterpret(ForwardDiff.Dual{T, V, P}, p)
             if cache.batch > 0
-                dx = similar(dualp, cache.nout, size(x, 2))
+                dx = cache.nout == 1 ? similar(dualp, size(x, ndims(x))) :
```
Comment (ChrisRackauckas) [inline ext/IntegralsForwardDiffExt.jl:32]: won't the nout = 1 case not be able to use `similar` because it could be scalar?

File: ext/IntegralsZygoteExt.jl [hunk 2]
```diff
@@ -44,14 +54,21 @@ function ChainRulesCore.rrule(::typeof(Integrals.__solvebp), cache, alg, senseal
             if sensealg.vjp isa Integrals.ZygoteVJP
                 if cache.batch > 0
                     dfdp = function (x, p)
-                        _, back = Zygote.pullback(p -> cache.f(x, p), p)
+                        z, back = Zygote.pullback(p -> cache.f(x, p), p)
+                        # messy, there are 4 cases, some better in forward mode than reverse
+                        # 1: length(y) == 1 and length(p) == 1
+                        # 2: length(y) >  1 and length(p) == 1
+                        # 3: length(y) == 1 and length(p) >  1
+                        # 4: length(y) >  1 and length(p) >  1
```
Comment (ChrisRackauckas) [inline ext/IntegralsZygoteExt.jl:62]: I'm not sure what this comment is here for? I mean, agreed these are the 4 cases and sometimes forward is better than reverse, but I don't understand why that's here 😅

File: ext/IntegralsZygoteExt.jl [hunk 3]
```diff
@@ -76,26 +93,39 @@ function ChainRulesCore.rrule(::typeof(Integrals.__solvebp), cache, alg, senseal
...
 end
 
-Zygote.@adjoint function Zygote.literal_getproperty(sol::SciMLBase.IntegralSolution,
-    ::Val{:u})
-    sol.u, Δ -> (SciMLBase.build_solution(sol.prob, sol.alg, Δ, sol.resid),)
-end
+# Zygote.@adjoint function Zygote.literal_getproperty(sol::SciMLBase.IntegralSolution,
+#     ::Val{:u})
+#     sol.u, Δ -> (SciMLBase.build_solution(sol.prob, sol.alg, Δ, sol.resid),)
+# end
```
Comment (ChrisRackauckas) [inline ext/IntegralsZygoteExt.jl:130]: Why was this removed?

**Comment by ChrisRackauckas** [comment]
In general looks great, just a few comments.

**Comment by ChrisRackauckas** [comment]
> Should we add these prototype containers to Integrals.jl or SciMLBase.jl?

SciMLBase.

File: ext/IntegralsZygoteExt.jl (hunk 3 above)
Comment (ChrisRackauckas) [reply ext/IntegralsZygoteExt.jl:130]: That just means a test didn't use `sol.u`. This is necessary for if the user getfield's on `u`. It should be added back for that case, preferably with a test since that seems to have been missed.

Comment (ChrisRackauckas) [inline ext/IntegralsZygoteExt.jl:130]:
```suggestion
Zygote.@adjoint function Zygote.literal_getproperty(sol::SciMLBase.IntegralSolution,
    ::Val{:u})
    sol.u, Δ -> (SciMLBase.build_solution(sol.prob, sol.alg, Δ, sol.resid),)
end
```
